export const MAX_LOCAL_VIDEO_PROCESSING_CONCURRENCY = 2;
export const MAX_AI_CONCURRENCY = 2;
export const MAX_KEYFRAME_DIMENSION = 512;
export const KEYFRAME_JPEG_QUALITY = 0.62;
export const MAX_KEYFRAMES_PER_SEGMENT = 2;
export const MAX_ANALYZE_SEGMENT_REQUEST_BYTES = 3.5 * 1024 * 1024;
