import type { EditingPace, EditingPlan, EditingPlanItem, EditingPlanRole } from "../../domain/types/index.ts";
import type { EditingPlanInput } from "../../features/editing-plan/editing-plan-input.ts";
import { EDITING_PLAN_DURATION_TOLERANCE, MIN_EDITING_CLIP_DURATION } from "../../features/editing-plan/config.ts";

export const editingPlanRoles: EditingPlanRole[] = ["hook", "setup", "context", "story_progression", "reaction", "contrast", "reveal", "transition", "b_roll", "peak", "ending"];
export const editingPaces: EditingPace[] = ["fast", "medium", "slow"];
const itemSchema = { type: "object", additionalProperties: false, properties: { segmentId: { type: "string" }, sourceVideoId: { type: "string" }, sourceStart: { type: "number" }, sourceEnd: { type: "number" }, role: { type: "string", enum: editingPlanRoles }, reason: { type: "string" }, narration: { type: ["string", "null"] }, subtitle: { type: ["string", "null"] }, editingNote: { type: ["string", "null"] }, transitionSuggestion: { type: ["string", "null"] }, pace: { type: "string", enum: editingPaces }, storyBeat: { type: "string" } }, required: ["segmentId", "sourceVideoId", "sourceStart", "sourceEnd", "role", "reason", "narration", "subtitle", "editingNote", "transitionSuggestion", "pace", "storyBeat"] } as const;
export const editingPlanJsonSchema = { type: "object", additionalProperties: false, properties: { title: { type: "string" }, timelineItems: { type: "array", minItems: 1, items: itemSchema } }, required: ["title", "timelineItems"] } as const;
const round = (value: number) => Math.round(value * 100) / 100;
export function recalculateTimeline(items: EditingPlanItem[]): EditingPlanItem[] { let cursor = 0; return items.map((item) => { const duration = round(item.sourceEnd - item.sourceStart); const next = { ...item, duration, timelineStart: round(cursor), timelineEnd: round(cursor + duration) }; cursor = next.timelineEnd; return next; }); }
export function validateEditingPlan(value: unknown, input: EditingPlanInput, metadata: { provider: string; model: string; createdAt: string }): EditingPlan {
  if (!value || typeof value !== "object") throw new Error("Editing plan is not an object"); const raw = value as Record<string, unknown>; if (typeof raw.title !== "string" || !raw.title.trim() || !Array.isArray(raw.timelineItems) || !raw.timelineItems.length) throw new Error("Invalid editing plan");
  const sources = new Map(input.segments.map((segment) => [segment.segmentId, segment])); const used = new Set<string>();
  const items = raw.timelineItems.map((entry): EditingPlanItem => { if (!entry || typeof entry !== "object") throw new Error("Invalid timeline item"); const item = entry as Record<string, unknown>; const source = sources.get(String(item.segmentId)); if (!source) throw new Error(`Unknown segment reference: ${String(item.segmentId)}`); if (used.has(source.segmentId)) throw new Error(`Duplicate segment reference: ${source.segmentId}`); used.add(source.segmentId); if (item.sourceVideoId !== source.sourceVideoId) throw new Error("Invalid source video reference"); const sourceStart = Number(item.sourceStart); const sourceEnd = Number(item.sourceEnd); if (!Number.isFinite(sourceStart) || !Number.isFinite(sourceEnd) || sourceStart < source.segmentStart || sourceEnd > source.segmentEnd || sourceEnd <= sourceStart) throw new Error("Source bounds are outside Segment"); if (sourceEnd - sourceStart < MIN_EDITING_CLIP_DURATION) throw new Error("Clip is shorter than minimum duration"); if (!editingPlanRoles.includes(item.role as EditingPlanRole) || !editingPaces.includes(item.pace as EditingPace) || typeof item.reason !== "string" || typeof item.storyBeat !== "string") throw new Error("Invalid editing metadata"); const nullable = (field: string) => typeof item[field] === "string" ? item[field] as string : null; return { id: crypto.randomUUID(), segmentId: source.segmentId, sourceVideoId: source.sourceVideoId, sourceStart: round(sourceStart), sourceEnd: round(sourceEnd), duration: 0, timelineStart: 0, timelineEnd: 0, role: item.role as EditingPlanRole, reason: item.reason, narration: nullable("narration"), subtitle: nullable("subtitle"), editingNote: nullable("editingNote"), transitionSuggestion: nullable("transitionSuggestion"), pace: item.pace as EditingPace, storyBeat: item.storyBeat }; });
  const timelineItems = recalculateTimeline(items); const totalDuration = timelineItems.at(-1)?.timelineEnd ?? 0; const target = input.story.estimatedDuration; if (target > 0 && (totalDuration < target * (1 - EDITING_PLAN_DURATION_TOLERANCE) || totalDuration > target * (1 + EDITING_PLAN_DURATION_TOLERANCE))) throw new Error("Editing plan duration is outside Story target tolerance");
  return { id: crypto.randomUUID(), storyId: input.story.id, title: raw.title, totalDuration, estimatedFinalDuration: totalDuration, timelineItems, ...metadata };
}
