import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import type { EditingPlanInput } from "../src/features/editing-plan/editing-plan-input.ts";
import { MIN_EDITING_CLIP_DURATION } from "../src/features/editing-plan/config.ts";
import { recalculateTimeline, validateEditingPlan } from "../src/server/editing/editing-plan-schema.ts";
import { QwenEditingPlanProvider } from "../src/server/editing/qwen-editing-plan-provider.ts";

const input: EditingPlanInput = { story: { id: "story-1", title: "真实旅程", hook: "从动作开始", estimatedDuration: 10, structure: [], segmentRefs: [] }, segments: [{ segmentId: "s1", sourceVideoId: "v1", sourceFileName: "A.mp4", segmentStart: 0, segmentEnd: 5, duration: 5 }, { segmentId: "s2", sourceVideoId: "v2", sourceFileName: "B.mp4", segmentStart: 10, segmentEnd: 15, duration: 5 }] };
const item = (segmentId: string, sourceVideoId: string, sourceStart: number, sourceEnd: number) => ({ segmentId, sourceVideoId, sourceStart, sourceEnd, role: segmentId === "s1" ? "hook" : "ending", reason: "真实动作支持", narration: null, subtitle: null, editingNote: "直接进入动作", transitionSuggestion: null, pace: "medium", storyBeat: segmentId === "s1" ? "Hook" : "Ending" });
const raw = { title: "剪辑方案", timelineItems: [item("s1", "v1", 0, 4), item("s2", "v2", 10, 14)] };
const validate = (value: unknown = raw) => validateEditingPlan(value, input, { provider: "qwen", model: "qwen3-vl-flash", createdAt: "now" });

test("Editing Plan validates real refs and calculates a continuous timeline", () => { const plan = validate(); assert.equal(plan.timelineItems[0].timelineStart, 0); assert.equal(plan.timelineItems[0].timelineEnd, 4); assert.equal(plan.timelineItems[1].timelineStart, 4); assert.equal(plan.timelineItems[1].timelineEnd, 8); assert.equal(plan.totalDuration, 8); });
test("unknown segmentId is rejected", () => assert.throws(() => validate({ ...raw, timelineItems: [item("missing", "v1", 0, 4)] }), /Unknown segment/));
test("source start and end bounds are enforced", () => { assert.throws(() => validate({ ...raw, timelineItems: [item("s1", "v1", -1, 4), item("s2", "v2", 10, 14)] }), /bounds/); assert.throws(() => validate({ ...raw, timelineItems: [item("s1", "v1", 0, 6), item("s2", "v2", 10, 14)] }), /bounds/); });
test("negative and too-short clips are rejected", () => { assert.equal(MIN_EDITING_CLIP_DURATION, 0.8); assert.throws(() => validate({ ...raw, timelineItems: [item("s1", "v1", 2, 1), item("s2", "v2", 10, 14)] }), /bounds/); assert.throws(() => validate({ ...raw, timelineItems: [item("s1", "v1", 0, 0.2), item("s2", "v2", 10, 14)] }), /minimum/); });
test("one Segment can appear only once", () => assert.throws(() => validate({ ...raw, timelineItems: [item("s1", "v1", 0, 4), item("s1", "v1", 0, 4)] }), /Duplicate/));
test("remove and move operations recalculate locally", () => { const plan = validate(); const moved = recalculateTimeline([plan.timelineItems[1], plan.timelineItems[0]]); assert.deepEqual(moved.map((entry) => entry.timelineStart), [0, 4]); const removed = recalculateTimeline(moved.slice(1)); assert.equal(removed[0].timelineStart, 0); assert.equal(removed[0].timelineEnd, 4); });
test("Editing Plan cache, explicit regenerate and failure isolation are wired", () => { const source = readFileSync(new URL("../src/features/project/project-session-context.tsx", import.meta.url), "utf8"); const block = source.slice(source.indexOf("const generateEditingPlan"), source.indexOf("const removeEditingPlanItem")); assert.match(block, /!regenerate && editingPlan/); assert.doesNotMatch(block, /setStoryCandidates|setSelectedStoryCandidateId/); assert.match(source, /generateEditingPlan\(Boolean\(editingPlan\)\)|generateEditingPlan/); });
test("Editing Plan input contains no image or video payload", () => { const source = readFileSync(new URL("../src/features/editing-plan/editing-plan-input.ts", import.meta.url), "utf8"); assert.doesNotMatch(source, /keyframe|base64|inlineData|previewUrl|thumbnailUrl|\bFile\b|\bBlob\b/); });
test("Qwen structured output produces one complete Editing Plan request", async () => { let calls = 0; const provider = new QwenEditingPlanProvider("test", async () => { calls += 1; return new Response(JSON.stringify({ choices: [{ message: { content: JSON.stringify(raw) } }] }), { status: 200 }); }, async () => {}); const plan = await provider.generate(input); assert.equal(calls, 1); assert.equal(plan.provider, "qwen"); assert.equal(plan.timelineItems.length, 2); });
test("invalid Qwen plan receives at most one repair", async () => { let calls = 0; const provider = new QwenEditingPlanProvider("test", async () => { calls += 1; return new Response(JSON.stringify({ choices: [{ message: { content: calls === 1 ? "{}" : JSON.stringify(raw) } }] }), { status: 200 }); }, async () => {}); await provider.generate(input); assert.equal(calls, 2); });
