import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import type { EditingPlanInput } from "../src/features/editing-plan/editing-plan-input.ts";
import { generateLocalEditingPlan } from "../src/features/editing-plan/local-editing-plan.ts";
import { buildEditingPlanInput } from "../src/features/editing-plan/editing-plan-input.ts";
import type { StoryCandidate, VideoAsset, VideoSegment } from "../src/domain/types/index.ts";

const input: EditingPlanInput = { story: { id: "story-1", title: "旅行故事", hook: "出发", estimatedDuration: 10, structure: [{ type: "hook", description: "先看动作", segmentRefs: ["b"] }, { type: "ending", description: "最后收束", segmentRefs: ["a"] }], segmentRefs: [{ segmentId: "a", role: "ending", reason: "适合结尾", suggestedStartTime: 10, suggestedEndTime: 14 }, { segmentId: "b", role: "hook", reason: "动作明确", suggestedStartTime: 2, suggestedEndTime: 5 }] }, segments: [{ segmentId: "a", sourceVideoId: "video-a", sourceFileName: "A.mp4", segmentStart: 10, segmentEnd: 14, duration: 4 }, { segmentId: "b", sourceVideoId: "video-b", sourceFileName: "B.mp4", segmentStart: 2, segmentEnd: 5, duration: 3 }] };

test("local Editing Plan follows Story structure and real Segment bounds", () => { const plan = generateLocalEditingPlan(input); assert.equal(plan.provider, "local"); assert.deepEqual(plan.timelineItems.map((item) => item.segmentId), ["b", "a"]); assert.deepEqual(plan.timelineItems.map((item) => [item.sourceStart, item.sourceEnd]), [[2, 5], [10, 14]]); assert.deepEqual(plan.timelineItems.map((item) => [item.timelineStart, item.timelineEnd]), [[0, 3], [3, 7]]); });
test("local Editing Plan path does not call its API route", () => { const source = readFileSync(new URL("../src/features/project/project-session-context.tsx", import.meta.url), "utf8"); const block = source.slice(source.indexOf("const generateEditingPlan"), source.indexOf("const removeEditingPlanItem")); assert.match(block, /generateLocalEditingPlan/); assert.doesNotMatch(block, /fetch\(|generate-editing-plan/); });
test("structure-only Segment refs remain exact and resolve into the local plan", () => { const story = { id: "story-2", title: "结构引用", angle: "真实", hook: "开始", summary: "摘要", score: 80, reasons: [], targetAudience: "观众", recommendedSegmentIds: ["a"], estimatedDuration: 7, segmentRefs: [{ segmentId: "a", role: "ending", reason: "结尾", suggestedStartTime: 10, suggestedEndTime: 14 }], structure: [{ type: "hook", description: "结构独有引用", segmentRefs: ["b"] }, { type: "ending", description: "结尾", segmentRefs: ["a"] }] } satisfies StoryCandidate; const segments = [{ id: "a", videoId: "video-a", startTime: 10, endTime: 14, duration: 4 }, { id: "b", videoId: "video-b", startTime: 2, endTime: 5, duration: 3 }].map((item) => ({ ...item, segmentationReason: "scene_boundary", transcript: null, visualDescription: null, scene: null, subjects: [], actions: [], visualQuality: null, informationValue: null, emotionalValue: null, novelty: null, audienceAppeal: null, possibleRoles: [], status: "ready" as const })) satisfies VideoSegment[]; const assets = [{ id: "video-a", fileName: "A.mp4" }, { id: "video-b", fileName: "B.mp4" }].map((asset) => ({ ...asset, fileType: "video/mp4", fileSize: 1, duration: 20, width: 1920, height: 1080, thumbnailUrl: null, status: "ready" as const, createdAt: "now" })) satisfies VideoAsset[]; const built = buildEditingPlanInput(story, segments, assets, {}, {}); assert.deepEqual(built.segments.map((segment) => segment.segmentId), ["a", "b"]); assert.deepEqual(generateLocalEditingPlan(built).timelineItems.map((item) => item.segmentId), ["b", "a"]); });
