import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import { buildStoryDiscoveryInput } from "../src/features/story-discovery/story-discovery-input.ts";
import { MAX_STORY_DISCOVERY_SEGMENTS } from "../src/features/story-discovery/config.ts";
import { storyTypeLabels } from "../src/features/story-discovery/ui-labels.ts";
import { validateStoryCandidates } from "../src/server/story/story-candidate-schema.ts";
import type { SegmentAnalysisResult, SegmentCandidateScore, VideoSegment } from "../src/domain/types/index.ts";

const segment = (id: string): VideoSegment => ({ id, videoId: `video-${id}`, startTime: 0, endTime: 5, duration: 5, segmentationReason: "scene_boundary", transcript: null, visualDescription: null, scene: null, subjects: [], actions: [], visualQuality: null, informationValue: null, emotionalValue: null, novelty: null, audienceAppeal: null, possibleRoles: [], status: "ready" });
const score = (id: string, tier: SegmentCandidateScore["tier"]): SegmentCandidateScore => ({ segmentId: id, overallScore: tier === "high" ? 80 : tier === "medium" ? 60 : 30, duplicatePenalty: 0, staticPenalty: 0, confidence: 0.75, reasons: [], tier, scoredAt: "now" });
const analysis = (id: string): SegmentAnalysisResult => ({ segmentId: id, visualDescription: "人物走过草地", scene: "户外", subjects: ["人物"], actions: ["行走"], cameraBehavior: "tracking", visualQuality: 80, informationValue: 60, emotionalValue: 70, novelty: 55, audienceAppeal: 65, possibleRoles: ["context"], momentSummary: "人物走向远处", provider: "gemini", model: "gemini-3.7-flash", analyzedAt: "now" });

test("Story Discovery reads only analyzed high and medium candidates", () => { const segments = [segment("h"), segment("m"), segment("l"), segment("missing")]; const scores = { h: score("h", "high"), m: score("m", "medium"), l: score("l", "low"), missing: score("missing", "high") }; const analyses = { h: analysis("h"), m: analysis("m"), l: analysis("l") }; assert.deepEqual(buildStoryDiscoveryInput(segments, scores, analyses).map(({ segmentId }) => segmentId).sort(), ["h", "m"]); });
test("compressed input sends neither keyframes nor video data", () => { const input = buildStoryDiscoveryInput([segment("h")], { h: score("h", "high") }, { h: analysis("h") }); const json = JSON.stringify(input); assert.doesNotMatch(json, /keyframe|base64|inlineData|thumbnail|previewUrl|fileType|fileSize/i); });
test("Story Discovery selection respects MAX_STORY_DISCOVERY_SEGMENTS", () => { const segments = Array.from({ length: 70 }, (_, index) => segment(String(index))); const scores = Object.fromEntries(segments.map(({ id }) => [id, score(id, "high")])); const analyses = Object.fromEntries(segments.map(({ id }) => [id, analysis(id)])); assert.equal(buildStoryDiscoveryInput(segments, scores, analyses).length, MAX_STORY_DISCOVERY_SEGMENTS); });

const sourceInputs = buildStoryDiscoveryInput([segment("a"), segment("b")], { a: score("a", "high"), b: score("b", "medium") }, { a: analysis("a"), b: analysis("b") });
function rawCandidate(title: string, type: string, ids: string[]) { return { title, concept: `${title}的概念`, storyType: type, hook: `${title}的开场`, coreIdea: `${title}的核心`, targetViewerValue: ["真实体验"], estimatedDuration: 10, segmentRefs: ids.map((segmentId, index) => ({ segmentId, role: index ? "ending" : "hook", reason: "真实素材支持", suggestedStartTime: 0, suggestedEndTime: 5 })), structure: [{ type: "hook", description: "进入", segmentRefs: [ids[0]] }, { type: "development", description: "发展", segmentRefs: ids }, { type: "ending", description: "结束", segmentRefs: [ids.at(-1)] }], whyItWorks: `${title}具有真实变化`, confidence: 75 }; }
test("one request can validate multiple meaningfully different stories", () => { const result = validateStoryCandidates({ candidates: [rawCandidate("人物反应", "character", ["a", "b"]), rawCandidate("环境探索", "discovery", ["b", "a"])] }, sourceInputs, { provider: "gemini", model: "test", createdAt: "now" }); assert.equal(result.length, 2); });
test("Story Candidate references must exist in the submitted input", () => assert.throws(() => validateStoryCandidates({ candidates: [rawCandidate("错误引用", "mixed", ["unknown"])] }, sourceInputs, { provider: "gemini", model: "test", createdAt: "now" }), /Unknown segment reference/));
test("Story Discovery accepts one candidate when material is insufficient", () => assert.equal(validateStoryCandidates({ candidates: [rawCandidate("单一方向", "experience", ["a"])] }, sourceInputs, { provider: "gemini", model: "test", createdAt: "now" }).length, 1));
test("Story Type mapping is Chinese", () => { assert.equal(storyTypeLabels.emotional, "情绪记录"); assert.equal(storyTypeLabels.discovery, "探索发现"); });
test("Story Discovery cache, selection and regeneration remain explicit", () => { const source = readFileSync(new URL("../src/features/project/project-session-context.tsx", import.meta.url), "utf8"); assert.match(source, /!regenerate && storyCandidatesRef\.current\.length > 0/); assert.match(source, /selectStoryCandidate[\s\S]*setSelectedStoryCandidateId/); assert.doesNotMatch(source, /useEffect\(\(\) => \{[^}]*discoverStories/); });
test("Story Discovery failure does not clear candidate scores or Segment analyses", () => { const source = readFileSync(new URL("../src/features/project/project-session-context.tsx", import.meta.url), "utf8"); const discovery = source.slice(source.indexOf("const discoverStories"), source.indexOf("const selectStoryCandidate")); assert.doesNotMatch(discovery, /setCandidateScores|setAnalysesBySegment/); });
