export const MAX_STORY_DISCOVERY_SEGMENTS = 24;
export const STORY_DISCOVERY_REQUEST_TIMEOUT_MS = 60_000;
export const STORY_DISCOVERY_MAX_ATTEMPTS = 1;
export const DEFAULT_STORY_CANDIDATE_COUNT = 3;
export const MIN_STORY_DISCOVERY_ANALYZED_SEGMENTS = 5;
