"use client";

import { useEffect, useState } from "react";
import type { StoryCandidate } from "@/domain/types";
import { useProjectSession } from "@/features/project/project-session-context";
import { storyBeatLabels, storyTypeLabels } from "@/features/story-discovery/ui-labels";
import { MIN_STORY_DISCOVERY_ANALYZED_SEGMENTS } from "@/features/story-discovery/config";

function time(seconds: number) { const minutes = Math.floor(seconds / 60); return `${String(minutes).padStart(2, "0")}:${(seconds % 60).toFixed(2).padStart(5, "0")}`; }
function modelLabel(model?: string) { if (!model) return "Provider pending"; return model.startsWith("qwen") ? `Qwen · ${model}` : model.replace(/^gemini-/, "Gemini ").replace(/-flash$/, " Flash"); }

export function StoryDiscoveryPanel() {
  const { storyCandidates, storyDiscovery, discoverStories, cancelStoryDiscovery, selectedStoryCandidateId, selectStoryCandidate, candidateScores, analysesBySegment } = useProjectSession();
  const [clock, setClock] = useState(0);
  useEffect(() => { if (storyDiscovery.status !== "cooldown") return; const timer = window.setInterval(() => setClock(Date.now()), 1000); return () => window.clearInterval(timer); }, [storyDiscovery.status]);
  const eligibleCount = Object.values(candidateScores).filter((score) => (score.tier === "high" || score.tier === "medium") && analysesBySegment[score.segmentId]).length;
  const active = ["preparing", "waiting", "cooldown", "discovering", "retrying", "switching_model"].includes(storyDiscovery.status);
  const cooldownSeconds = storyDiscovery.cooldownUntil && clock ? Math.max(0, Math.ceil((storyDiscovery.cooldownUntil - clock) / 1000)) : 0;
  return <section className="mt-8 border border-black/10 bg-[var(--paper)] p-6 md:p-8"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[var(--accent)]">Story Discovery</p><div className="mt-3 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-2xl font-medium">{storyDiscoveryTitle(storyDiscovery.status)}</h2><p className="mt-2 text-sm text-black/40">只使用已理解的 high / medium 结构化摘要，不重新发送图片或视频。</p></div>{!active && eligibleCount >= MIN_STORY_DISCOVERY_ANALYZED_SEGMENTS && <button className="bg-[var(--ink)] px-5 py-3 text-sm text-white" onClick={() => void discoverStories(storyCandidates.length > 0)} type="button">{storyCandidates.length ? "重新发现故事（再次调用 AI）" : "发现故事方向"}</button>}{active && <button className="text-xs underline decoration-black/20 underline-offset-4" onClick={cancelStoryDiscovery} type="button">取消</button>}</div>{active && <p className="mt-5 text-sm text-black/50">{storyDiscoveryDetail(storyDiscovery.status, storyDiscovery.model, storyDiscovery.attempt, storyDiscovery.maxAttempts, cooldownSeconds)}</p>}{storyDiscovery.status === "error" && <p className="mt-5 text-sm text-[var(--accent)]">{storyDiscovery.error}</p>}{storyDiscovery.inputSegmentCount !== undefined && storyDiscovery.candidateSegmentCount !== undefined && <p className="mt-4 text-xs text-black/35">基于 {storyDiscovery.inputSegmentCount} 个已理解片段生成，另有 {Math.max(0, storyDiscovery.candidateSegmentCount - storyDiscovery.inputSegmentCount)} 个候选片段暂未纳入。</p>}{process.env.NODE_ENV === "development" && storyDiscovery.inputSegmentCount !== undefined && <div className="mt-5 border-t border-black/10 pt-4 font-mono text-[10px] leading-5 text-black/30"><p>Story Discovery Input Preview</p><p>{storyDiscovery.inputSegmentCount} segments · {storyDiscovery.payloadBytes ?? 0} bytes · high {storyDiscovery.highCount ?? 0} · medium {storyDiscovery.mediumCount ?? 0} · {modelLabel(storyDiscovery.model)}</p><p>AI Scheduler · active {storyDiscovery.activeRequests ?? 0} · queued {storyDiscovery.queuedRequests ?? 0} · cooldown {cooldownSeconds}s</p></div>}{storyCandidates.length > 0 && <div className="mt-8 grid gap-5 xl:grid-cols-3">{storyCandidates.map((story) => <StoryCard key={story.id} story={story} selected={selectedStoryCandidateId === story.id} onSelect={() => selectStoryCandidate(story.id)} />)}</div>}{selectedStoryCandidateId && <p className="mt-6 border-t border-black/10 pt-5 text-sm font-medium">已选择故事方向，可在下方生成 Editing Plan。</p>}{eligibleCount < MIN_STORY_DISCOVERY_ANALYZED_SEGMENTS && storyCandidates.length === 0 && <p className="mt-5 text-sm text-black/40">至少需要 {MIN_STORY_DISCOVERY_ANALYZED_SEGMENTS} 个 high / medium 候选片段完成 AI 理解（当前 {eligibleCount} 个）。</p>}</section>;
}

function StoryCard({ story, selected, onSelect }: { story: StoryCandidate; selected: boolean; onSelect: () => void }) {
  const [expanded, setExpanded] = useState(false); const { assets, segmentsByVideo, segmentThumbnailUrls } = useProjectSession();
  const segments = Object.values(segmentsByVideo).flat();
  return <article className={`border p-5 ${selected ? "border-[var(--accent)]" : "border-black/10"}`}><p className="text-[10px] uppercase tracking-[0.14em] text-[var(--accent)]">{story.storyType ? storyTypeLabels[story.storyType] : "故事方向"}</p><h3 className="mt-3 text-2xl font-medium tracking-[-0.035em]">{story.title}</h3><p className="mt-4 text-sm leading-6 text-black/55">{story.concept ?? story.angle}</p><div className="mt-5 grid grid-cols-2 gap-px bg-black/10"><Meta label="预计时长" value={`${Math.round(story.estimatedDuration)} 秒`} /><Meta label="使用素材" value={`${story.segmentRefs?.length ?? story.recommendedSegmentIds.length} 个片段`} /></div><div className="mt-5"><p className="text-[10px] text-black/30">开场方式</p><p className="mt-2 text-sm leading-6">{story.hook}</p><p className="mt-4 text-[10px] text-black/30">为什么成立</p><p className="mt-2 text-sm leading-6 text-black/55">{story.whyItWorks ?? story.reasons[0]}</p></div>{expanded && <div className="mt-5 border-t border-black/10 pt-5"><p className="text-xs font-medium">核心主题</p><p className="mt-2 text-xs leading-5 text-black/50">{story.coreIdea ?? story.summary}</p><p className="mt-4 text-xs font-medium">目标观众价值</p><p className="mt-2 text-xs text-black/50">{story.targetViewerValue?.join(" · ") ?? story.targetAudience}</p><div className="mt-5 space-y-5">{story.structure.map((beat, index) => <div key={`${story.id}-${index}`}><p className="text-[10px] uppercase tracking-[0.12em] text-black/30">{String(index + 1).padStart(2, "0")} / {beat.type ? storyBeatLabels[beat.type] : beat.role}</p><p className="mt-1 text-xs leading-5">{beat.description ?? beat.purpose}</p></div>)}</div><div className="mt-6 space-y-3">{story.segmentRefs?.map((ref) => { const segment = segments.find((item) => item.id === ref.segmentId); const asset = assets.find((item) => item.id === segment?.videoId); return <div className="flex gap-3 border-t border-black/10 pt-3" key={ref.segmentId}><div className="h-14 w-24 shrink-0 bg-black/5 bg-cover bg-center" style={segmentThumbnailUrls[ref.segmentId] ? { backgroundImage: `url(${segmentThumbnailUrls[ref.segmentId]})` } : undefined} /><div className="min-w-0"><p className="truncate text-xs font-medium">{asset?.fileName ?? "Local video"}</p><p className="mt-1 font-mono text-[10px] text-black/40">{time(ref.suggestedStartTime)} → {time(ref.suggestedEndTime)}</p><p className="mt-1 text-[10px] leading-4 text-black/45">{storyBeatLabels[ref.role]} · {ref.reason}</p></div></div>; })}</div><p className="mt-5 font-mono text-[10px] text-black/25">{story.provider} / {story.model}</p></div>}<div className="mt-6 flex flex-wrap gap-4"><button className="text-xs underline decoration-black/20 underline-offset-4" onClick={() => setExpanded((value) => !value)} type="button">{expanded ? "收起故事结构" : "查看故事结构"}</button><button className="text-xs font-medium underline decoration-black/20 underline-offset-4" onClick={onSelect} type="button">{selected ? "已选择这个方向" : "选择这个方向"}</button></div></article>;
}

function Meta({ label, value }: { label: string; value: string }) { return <div className="bg-[var(--paper)] p-3"><p className="text-[10px] text-black/30">{label}</p><p className="mt-1 text-sm">{value}</p></div>; }
function storyDiscoveryTitle(status: string) { if (status === "preparing") return "正在整理已理解的候选片段"; if (status === "waiting") return "正在等待当前素材理解任务完成…"; if (status === "cooldown") return "AI 服务请求较多，正在等待可用额度…"; if (["discovering", "retrying", "switching_model"].includes(status)) return "正在寻找故事线"; if (status === "ready") return "Story Candidates Ready"; if (status === "error") return "故事发现暂未完成"; return "这些素材可以讲什么？"; }
function storyDiscoveryDetail(status: string, model?: string, attempt?: number, maxAttempts?: number, cooldownSeconds = 0) { if (status === "cooldown") return `约 ${cooldownSeconds} 秒后自动继续`; if (status === "waiting") return "已进入 AI 高优先级队列，当前执行中的请求会先完成。"; if (status === "retrying") return `${modelLabel(model)} 暂时繁忙 · 正在重试 ${attempt ?? "—"} / ${maxAttempts ?? 2}`; if (status === "switching_model") return `主模型暂时繁忙，正在切换至 ${modelLabel(model)}`; return `${modelLabel(model)} 正在分析素材之间的关系`; }
