import type { SegmentAnalysisResult, SegmentCandidateScore, StoryCandidate, VideoAsset, VideoSegment } from "../../domain/types/index.ts";

export interface EditingPlanSegmentInput { segmentId: string; sourceVideoId: string; sourceFileName: string; segmentStart: number; segmentEnd: number; duration: number; candidateScore?: number; candidateTier?: string; momentSummary?: string; visualDescription?: string; scene?: string; subjects?: string[]; actions?: string[]; possibleRoles?: string[] }
export interface EditingPlanInput { story: Pick<StoryCandidate, "id" | "title" | "concept" | "hook" | "coreIdea" | "estimatedDuration" | "structure" | "segmentRefs">; segments: EditingPlanSegmentInput[] }

export function buildEditingPlanInput(story: StoryCandidate, segments: VideoSegment[], assets: VideoAsset[], analyses: Record<string, SegmentAnalysisResult>, scores: Record<string, SegmentCandidateScore>): EditingPlanInput {
  const segmentMap = new Map(segments.map((segment) => [segment.id, segment])); const assetMap = new Map(assets.map((asset) => [asset.id, asset]));
  const ids = [...new Set([...(story.segmentRefs?.map((ref) => ref.segmentId) ?? story.recommendedSegmentIds), ...story.structure.flatMap((beat) => beat.segmentRefs ?? beat.segmentIds ?? [])])];
  return { story: { id: story.id, title: story.title, concept: story.concept, hook: story.hook, coreIdea: story.coreIdea, estimatedDuration: story.estimatedDuration, structure: story.structure, segmentRefs: story.segmentRefs }, segments: ids.map((id) => { const segment = segmentMap.get(id); if (!segment) throw new Error(`Unknown story segment: ${id}`); const asset = assetMap.get(segment.videoId); if (!asset) throw new Error(`Unknown source video: ${segment.videoId}`); const analysis = analyses[id]; const score = scores[id]; return { segmentId: id, sourceVideoId: segment.videoId, sourceFileName: asset.fileName, segmentStart: segment.startTime, segmentEnd: segment.endTime, duration: segment.duration, candidateScore: score?.overallScore, candidateTier: score?.tier, momentSummary: analysis?.momentSummary, visualDescription: analysis?.visualDescription, scene: analysis?.scene, subjects: analysis?.subjects, actions: analysis?.actions, possibleRoles: analysis?.possibleRoles }; }) };
}
