import type { StoryBeatType, StoryCandidate, StoryType } from "@/domain/types";
import type { StoryDiscoverySegmentInput } from "@/features/story-discovery/story-discovery-input";

export const storyTypes: StoryType[] = ["emotional", "informational", "experience", "aesthetic", "character", "discovery", "mixed"];
export const storyBeatTypes: StoryBeatType[] = ["hook", "setup", "development", "contrast", "peak", "transition", "ending"];
const segmentRefSchema = { type: "object", additionalProperties: false, properties: { segmentId: { type: "string" }, role: { type: "string", enum: storyBeatTypes }, reason: { type: "string" }, suggestedStartTime: { type: "number" }, suggestedEndTime: { type: "number" } }, required: ["segmentId", "role", "reason", "suggestedStartTime", "suggestedEndTime"] } as const;
const beatSchema = { type: "object", additionalProperties: false, properties: { type: { type: "string", enum: storyBeatTypes }, description: { type: "string" }, segmentRefs: { type: "array", items: { type: "string" }, minItems: 1 } }, required: ["type", "description", "segmentRefs"] } as const;
export const storyDiscoveryJsonSchema = { type: "object", additionalProperties: false, properties: { candidates: { type: "array", minItems: 1, maxItems: 3, items: { type: "object", additionalProperties: false, properties: { title: { type: "string" }, concept: { type: "string" }, storyType: { type: "string", enum: storyTypes }, hook: { type: "string" }, coreIdea: { type: "string" }, targetViewerValue: { type: "array", items: { type: "string" }, minItems: 1, maxItems: 5 }, estimatedDuration: { type: "number" }, segmentRefs: { type: "array", items: segmentRefSchema, minItems: 1 }, structure: { type: "array", items: beatSchema, minItems: 3, maxItems: 5 }, whyItWorks: { type: "string" }, confidence: { type: "integer", minimum: 0, maximum: 100 } }, required: ["title", "concept", "storyType", "hook", "coreIdea", "targetViewerValue", "estimatedDuration", "segmentRefs", "structure", "whyItWorks", "confidence"] } } }, required: ["candidates"] } as const;

const text = (value: unknown): value is string => typeof value === "string" && value.trim().length > 0;
const textArray = (value: unknown): value is string[] => Array.isArray(value) && value.length > 0 && value.every(text);
function received(value: unknown) { if (value === undefined) return "undefined"; if (value === null) return "null"; if (Array.isArray(value)) return "array"; return typeof value; }
export function validateStoryCandidates(value: unknown, sourceSegments: StoryDiscoverySegmentInput[], metadata: { provider: string; model: string; createdAt: string }): StoryCandidate[] {
  if (!value || typeof value !== "object" || !Array.isArray((value as { candidates?: unknown }).candidates)) throw new Error("Story response must contain candidates");
  const rawCandidates = (value as { candidates: unknown[] }).candidates;
  if (rawCandidates.length < 1 || rawCandidates.length > 3) throw new Error("Story response must contain 1–3 candidates");
  const sources = new Map(sourceSegments.map((segment) => [segment.segmentId, segment]));
  const candidates = rawCandidates.map((raw, candidateIndex): StoryCandidate => {
    if (!raw || typeof raw !== "object" || Array.isArray(raw)) throw new Error(`candidate[${candidateIndex}] expected object, received ${received(raw)}`); const item = raw as Record<string, unknown>;
    for (const field of ["title", "concept", "hook", "coreIdea", "whyItWorks"]) if (!text(item[field])) throw new Error(`candidate[${candidateIndex}].${field} expected non-empty string, received ${received(item[field])}`);
    if (!storyTypes.includes(item.storyType as StoryType) || !textArray(item.targetViewerValue) || typeof item.estimatedDuration !== "number" || item.estimatedDuration <= 0 || !Number.isInteger(item.confidence) || (item.confidence as number) < 0 || (item.confidence as number) > 100) throw new Error("Invalid story metadata");
    if (!Array.isArray(item.segmentRefs) || !item.segmentRefs.length) throw new Error("Story must reference segments");
    const refs = item.segmentRefs.map((rawRef) => { const ref = rawRef as Record<string, unknown>; const source = sources.get(ref.segmentId as string); if (!source) throw new Error(`Unknown segment reference: ${String(ref.segmentId)}`); if (!storyBeatTypes.includes(ref.role as StoryBeatType) || !text(ref.reason)) throw new Error("Invalid segment role/reason"); return { segmentId: source.segmentId, role: ref.role as StoryBeatType, reason: ref.reason, suggestedStartTime: source.startTime, suggestedEndTime: source.endTime }; });
    if (!Array.isArray(item.structure) || item.structure.length < 3 || item.structure.length > 5) throw new Error("Story structure must contain 3–5 beats");
    const structure = item.structure.map((rawBeat, index) => { const beat = rawBeat as Record<string, unknown>; if (!storyBeatTypes.includes(beat.type as StoryBeatType) || !text(beat.description) || !textArray(beat.segmentRefs) || beat.segmentRefs.some((id) => !sources.has(id))) throw new Error("Invalid story beat"); return { order: index + 1, type: beat.type as StoryBeatType, description: beat.description, segmentRefs: beat.segmentRefs }; });
    const confidence = item.confidence as number; const concept = item.concept as string; const coreIdea = item.coreIdea as string;
    return { id: crypto.randomUUID(), title: item.title as string, angle: concept, hook: item.hook as string, summary: coreIdea, score: confidence, reasons: [item.whyItWorks as string], targetAudience: (item.targetViewerValue as string[]).join("、"), recommendedSegmentIds: refs.map((ref) => ref.segmentId), structure, estimatedDuration: item.estimatedDuration as number, concept, storyType: item.storyType as StoryType, coreIdea, targetViewerValue: item.targetViewerValue as string[], segmentRefs: refs, whyItWorks: item.whyItWorks as string, confidence, ...metadata };
  });
  for (let first = 0; first < candidates.length; first += 1) for (let second = first + 1; second < candidates.length; second += 1) { const a = candidates[first]; const b = candidates[second]; const differences = Number(a.storyType !== b.storyType) + Number(a.hook !== b.hook) + Number(a.coreIdea !== b.coreIdea) + Number(a.recommendedSegmentIds.join() !== b.recommendedSegmentIds.join()); if (differences < 2) throw new Error("Story candidates are not meaningfully different"); }
  return candidates;
}
